### ISSUE TITLE
Seems not working on Sketch 3.4.4

### ISSUE THREAD

**Issue by pericn** [lukasondrej/sketch-comments#2]
Initialising nor adding comments is working.

**Comment by danielone** [comment]
Any updates for 3.4.4 planned?

**Comment by i849301** [comment]
Also having this problem.

**Comment by lukasondrej** [comment]
Thanks for letting me know, I'll take a look at it.

**Comment by lukasondrej** [comment]
The new plugin is out! Use [Sketch Focus](https://github.com/lukasondrej/sketch-focus) instead.
