### ISSUE TITLE
not working on sketch 3.6.1

### ISSUE THREAD

**Issue by xiaokun** [lukasondrej/sketch-comments#3]
successfull Initialized but adding comments shows nothing

**Comment by buughost** [comment]
Also not working for Sketch 3.6

**Comment by lkoeln** [comment]
i have the same issue on Version 3.6.1. I installed the plugin manually

**Comment by flavonese** [comment]
I have same issue Version 3.8.3 (29802). Did not successfully initialise and I manually created the "point", "text" and "bg" and still cannot add any comment. Hope someone can help.

**Comment by Xample** [comment]
Same problem, 3.8.3

**Comment by lukasondrej** [comment]
The new plugin is out! Use [Sketch Focus](https://github.com/lukasondrej/sketch-focus) instead.
